### ISSUE TITLE
Show alternative example commands to docker

### ISSUE THREAD

**Issue by sysrich** [M0ses/cooverview#1]
cooverview is always showing a docker example command for each container

eg `docker pull registry.opensuse.org/devel/caasp/1.0/container/kubic/salt-api:2018.3.0`

Kubic is installing podman by default, so it would be nice if cooverview showed that equivalent command in addition

Syntax is very similar

eg  `podman pull registry.opensuse.org/devel/caasp/1.0/container/kubic/salt-api:2018.3.0`

**Comment by M0ses** [comment]
even if I understand the intension - I don`t like the idea of changing docker -> podman in the "docker pull" command - I think podman is not so well known and widely used as docker - I would prefer a modal window to select docker or podman and store it in a cookie
