### ISSUE TITLE
[Feature request]: Arch filter

### ISSUE THREAD

**Issue by MalloZup** [M0ses/cooverview#10]
It would be nice to have abutton for filtering out the image by architecture

**Comment by M0ses** [comment]
If we would like to filter out all repos that have an container with a specific arch, this will get quite expensive and adding a filter which only supresses "non-selected" images when opening the details - this would result in an broken user experience - Anyway - Feel free to open a new issue (only copy/paste) in our new official GH repo

https://github.com/openSUSE/cooverview
