### ISSUE TITLE
Don't show all images at once

### ISSUE THREAD

**Issue by sebastian-philipp** [M0ses/cooverview#2]
There are now too many images in order to show them all in one page. With so many items, it's loosing its usefulness. 

My personal use cases right now are:

1. I'd like to find all images of a user or a project
2. I'd like to find all images containing some substring. 
3. An overview about the general hierarchy

**Comment by thkukuk** [comment]
I fully agree. What we need are three tabs:
1. "Official" openSUSE images build in openSUSE:Factory
2. "Devel" projects, everything not in 1. or starting with "home".
3. "Home" projects
