### ISSUE TITLE
Please, don't show modal dialog 

### ISSUE THREAD

**Issue by sebastian-philipp** [M0ses/cooverview#8]
![Screenshot_20190329_125128](https://user-images.githubusercontent.com/2574405/55230959-a492e700-5221-11e9-9bd4-089b8da33b3d.png)

Please don't force users choose between podman and docker, as this is bad user experience.

Having an option in the first bootstrap container is ok, but please don't force all users to read the modal dialog.

**Comment by M0ses** [comment]
Thanks for your report

In general the idea behind the modal window is to be shown once when he enters the site the first time , force a selection and give a hint how to change this settings afterwards. 
I have to admit that it was not intended to be shown every time you restart your browser.
I will set the expiry time to 1 year.
