### ISSUE TITLE
Display size of image 

### ISSUE THREAD

**Issue by rfrohl** [M0ses/cooverview#9]
Would it be possible to display the size of an image ?

One of the criteria that I look for is how big the image is. This information is not displayed at the moment. Would it be possible to provide that somehow?

**Comment by thkukuk** [comment]
I second this, we really need to provide the size of the images.

**Comment by M0ses** [comment]
fixed with https://github.com/M0ses/cooverview/commit/a94f958f3f042b32a0dc37385938f3968af484d4
